apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: raj80dockerid/test:latest
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flaskdemo
